version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: arquidb
    ports:
      - "3306:3306"



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: arqui-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "9000:80"
    depends_on:
      - db
  mongodb:
    image: mongo:latest # Imagen oficial de MongoDB
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017" # Puerto estándar de MongoDB
    environment:
    # Opcional: Define un usuario/contraseña root para administración
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    # Opcional: Puedes crear una base de datos inicial, si lo necesitas
      MONGO_INITDB_DATABASE: db_scooter


