spring:
    data:
      mongodb:
        uri: mongodb://mongouser:mongopassword@localhost:27017/db_scooter?authSource=admin

server:
  port: 8083 # Puerto diferente si el microservicio de Usuario estï¿½ en 8081
