spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iaDB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8095


groq:
  api-key: ${GROQ_API_KEY}
  base-url: https://api.groq.com/openai
  model: llama-3.1-8b-instant   # o llama3-70b-8192 si querés más calidad
  temperature: 0.3
