#spring:
#  application:
#    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8081

server:
  port: 8090


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    gateway:
      server:
        webmvc:
          routes:
                      - id: user-service
                        uri: http://localhost:8001
                        predicates:
                          - Path=/api/usuarios/**

                      - id: trip-service
                        uri: http://localhost:8081
                        predicates:
                          - Path=/api/viajes/**


                      - id: scooter-service
                        uri: http://localhost:8083
                        predicates:
                          - Path=/api/monopatines/**

                      - id: billing-service
                        uri: http://localhost:8086
                        predicates:
                          - Path=/api/facturas/**


                      - id: stop-service
                        uri: http://localhost:8084
                        predicates:
                          - Path=/api/paradas/**

                      - id: iachat-service
                        uri: http://localhost:8095
                        predicates:
                          - Path=/api/iachat/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG